/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Divider: React.FC = () => {
  return (
    <hr className="self-stretch mt-16 w-full border border-solid border-neutral-700" />
  );
};

export default Divider;
