/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SectionTitleProps {
  title: string;
}

const SectionTitle: React.FC<SectionTitleProps> = ({ title }) => {
  return (
    <header className="flex gap-2 items-end text-xl md:text-3xl text-center text-neutral-300 font-GeneralSans px-2">
      <div>
        <h2 className="grow">{title}</h2>
      </div>
      <div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/06b297ac03d999e777186f23e7e39f52d5fe8d796badfaa2584c31646fde01ef?placeholderIfAbsent=true&apiKey=f1716b67ec4e483e95e723d993b0aceb"
          className="object-contain shrink-0 self-start w-6 md:w-8 aspect-square"
          alt=""
        />
      </div>
    </header>
  );
};

export default SectionTitle;
