/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SectionContentProps {
  content: string;
}

const SectionContent: React.FC<SectionContentProps> = ({ content }) => {
  return (
    <p className="mt-5 text-[16px] md:text-xl text-offwhite font-GeneralSans px-2">
      {content}
    </p>
  );
};

export default SectionContent;
