/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SectionTitle from "./SectionTitle";
import SectionContent from "./SectionContent";
import Divider from "./Divider";

interface WhoWeAreProps {
  title: string;
  content: string;
}

const WhoWeAre: React.FC<WhoWeAreProps> = ({ title, content }) => {
  return (
    <section className="flex flex-col items-start  md:max-w-7xl py-4 mx-auto">
      <SectionTitle title={title} />
      <SectionContent content={content} />
      <Divider />
    </section>
  );
};

export default WhoWeAre;
