/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Divider from "../WhoWeAre/Divider";

interface StatisticProps {
  value: string;
  label: string;
}

const Statistic: React.FC<StatisticProps> = ({ value, label }) => (
  <div className="flex flex-wrap  flex-col flex-1 justify-center px-1.5 py-6 min-h-[101px]">
    <div className="text-3xl font-InstrumentSerif italic">{value}</div>
    <div className="text-base tracking-tight">{label}</div>
  </div>
);

interface StatisticsCardProps {
  title: string;
  statistics: StatisticProps[];
}

const StatisticsCard: React.FC<StatisticsCardProps> = ({
  title,
  statistics,
}) => {
  return (
    <section className="flex flex-col text-center text-offwhite md:max-w-7xl px-2 py-4 mx-auto ">
      <Divider/>
      <h2 className="self-center ml-3 text-xl text-offwhite md:text-3xl mt-12 md:my-12">{title}</h2>
      <div className="flex flex-col md:flex-row flex-wrap mt-7 whitespace-nowrap">
        {statistics.map((stat, index) => (
          <Statistic key={index} value={stat.value} label={stat.label} />
        ))}
      </div>
    </section>
  );
};

export default StatisticsCard;
