/**
 * This code was generated by Builder.io.
 */
import React from "react";

type ContactInfoProps = {
  phone: string;
  email: string;
  address: string;
  postalCode: string;
};

const ContactInfo: React.FC<ContactInfoProps> = ({
  phone,
  email,
  address,
  postalCode,
}) => (
  <address className="flex flex-col items-start font-medium text-offwhite whitespace-nowrap font-GeneralSans ">
    <p>{phone}</p>
    <p>{email}</p>
    <p>{address}</p>
    <p>{postalCode}</p>
  </address>
);

export default ContactInfo;
