/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ImageContainerProps {
  src: string;
  alt: string;
}

const ImageContainer: React.FC<ImageContainerProps> = ({ src, alt }) => {
  return (
    <div className="flex flex-col mt-14 w-full rounded">
      <img
        loading="lazy"
        src={src}
        alt={alt}
        className="object-contain w-full md:w-[700px] mx-auto  rounded"
      />
    </div>
  );
};

export default ImageContainer;
